name: Build an angular project 
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name : push to staging server with ssh
        env :
            SSHPASS : ${{ secrets.SSHPASS }}
            SERVER : ${{ secrets.SERVER}}
        run : |
            sudo apt-get update 
            sudo apt-get install sshpass -y
            npm install -g @angular/cli
            npm ci --debug
            ng build --prod
            cd dist/catalogues-ui/
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - name: Build and push
        env:
           HEROKU_TOKEN : ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:push --app catalogues-ui web
      - name: Release
        env:
           HEROKU_TOKEN : ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:release --app catalogues-ui web 
      - name: heroku ps:scale 
        env:
           HEROKU_TOKEN : ${{ secrets.HEROKU_TOKEN }}
        run: heroku ps:scale web=1 --app catalogues-ui
